Traceback (most recent call last):
  File "eval.py", line 117, in <module>
    cortexode_wm.load_state_dict(torch.load(model_dir+'model_wm_'+data_name+'_'+surf_hemi+'_'+tag+'.pt', map_location=device))
  File "/opt/miniconda3/envs/cortexode/lib/python3.7/site-packages/torch/serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/miniconda3/envs/cortexode/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/miniconda3/envs/cortexode/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/cortexode/ckpts/experiment_6_A100/model/model_wm_adni_lh_exp6.pt'
Traceback (most recent call last):
  File "eval.py", line 117, in <module>
    cortexode_wm.load_state_dict(torch.load(model_dir+'model_wm_'+data_name+'_'+surf_hemi+'_'+tag+'.pt', map_location=device))
  File "/opt/miniconda3/envs/cortexode/lib/python3.7/site-packages/torch/serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/miniconda3/envs/cortexode/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/miniconda3/envs/cortexode/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/cortexode/ckpts/experiment_6_A100/model/model_wm_adni_rh_exp6.pt'
